// This file is automatically generated. Do not modify it manually.
export const firebaseConfig = {
  "apiKey": "AIzaSyBVB-JOMitwocBeQvmcdSkP42gDoral3Ws",
  "authDomain": "universe-35ffc.firebaseapp.com",
  "projectId": "universe-35ffc",
  "storageBucket": "universe-35ffc.appspot.com",
  "messagingSenderId": "665136260667",
  "appId": "1:665136260667:web:f9061eec388806e7b71e1e"
};
