'use client';

import { useState, useEffect, useCallback } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import {
  generatePersonalizedProjectIdeas,
  type GeneratePersonalizedProjectIdeasOutput,
} from '@/ai/flows/generate-personalized-project-ideas';
import { Button } from '@/components/ui/button';
import {
  Form,
  FormControl,
  FormDescription,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from '@/components/ui/form';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from '@/components/ui/accordion';
import { Bot, Loader2, BookOpen, Share2, History, Trash2, CheckSquare, Square, Download, X } from 'lucide-react';
import { toast } from 'sonner';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from './ui/select';
import { useAuth } from '@/context/AuthContext';
import { db } from '@/lib/firebase';
import { addDoc, collection, serverTimestamp } from 'firebase/firestore';
import { errorEmitter } from '@/firebase/error-emitter';
import { FirestorePermissionError } from '@/firebase/errors';
import type { GeneratePersonalizedProjectIdeasInput } from '@/ai/flows/generate-personalized-project-ideas';
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from './ui/alert-dialog';

const formSchema = z.object({
  skills: z.string().min(2, {
    message: 'Please list at least one skill.',
  }),
  interests: z.string().min(2, {
    message: 'Please list at least one interest.',
  }),
  projectPreferences: z.string().optional(),
});

const shareFormSchema = z.object({
  title: z.string().min(5, 'Title must be at least 5 characters.'),
  content: z.string().min(20, 'Content must be at least 20 characters.'),
  community: z.string().min(1, 'Please select a community.'),
});

type ProjectIdea = GeneratePersonalizedProjectIdeasOutput['projectIdeas'][0];

interface ShareIdeaDialogProps {
  idea: ProjectIdea | null;
  isOpen: boolean;
  onOpenChange: (isOpen: boolean) => void;
  onPost: () => void;
}

interface GenerationHistoryItem {
    id: string;
    timestamp: number;
    input: GeneratePersonalizedProjectIdeasInput;
    output: GeneratePersonalizedProjectIdeasOutput;
}

const communities = ['General', 'AI/ML', 'WebDev', 'Design', 'Startups', 'Gaming'];

function useLocalStorage<T>(key: string, initialValue: T): [T, (value: T | ((val: T) => T)) => void] {
    const [storedValue, setStoredValue] = useState<T>(() => {
        if (typeof window === 'undefined') {
            return initialValue;
        }
        try {
            const item = window.localStorage.getItem(key);
            return item ? JSON.parse(item) : initialValue;
        } catch (error) {
            console.error(error);
            return initialValue;
        }
    });

    const setValue = (value: T | ((val: T) => T)) => {
        try {
            const valueToStore = value instanceof Function ? value(storedValue) : value;
            setStoredValue(valueToStore);
            if (typeof window !== 'undefined') {
                window.localStorage.setItem(key, JSON.stringify(valueToStore));
            }
        } catch (error) {
            console.error(error);
        }
    };
    return [storedValue, setValue];
}


function ShareIdeaDialog({ idea, isOpen, onOpenChange, onPost }: ShareIdeaDialogProps) {
  const { user } = useAuth();
  const [isSubmitting, setIsSubmitting] = useState(false);

  const form = useForm<z.infer<typeof shareFormSchema>>({
    resolver: zodResolver(shareFormSchema),
    defaultValues: {
      title: idea?.title || '',
      content: `${idea?.description}\n\n**Relevant Resources:**\n${idea?.relevantResources.join('\n- ')}\n\n---\n*🤖 Generated by uniVerse AI*`,
      community: 'General',
    },
  });

   useEffect(() => {
    if (idea) {
      form.reset({
        title: idea.title,
        content: `${idea.description}\n\n**Relevant Resources:**\n- ${idea.relevantResources.join('\n- ')}\n\n---\n*🤖 Generated by uniVerse AI*`,
        community: 'General',
      });
    }
   }, [idea, form]);

  const handleSubmit = async (values: z.infer<typeof shareFormSchema>) => {
    if (!db || !user || !idea) return;

    setIsSubmitting(true);
    const postData = {
      title: values.title,
      content: values.content,
      community: values.community,
      authorId: user.id,
      upvotes: [],
      comments: 0,
      createdAt: serverTimestamp(),
      updatedAt: serverTimestamp(),
      isAiGenerated: true,
    };

    const collectionRef = collection(db, 'forumPosts');
    const promise = addDoc(collectionRef, postData);

    toast.promise(promise, {
      loading: 'Posting to community...',
      success: () => {
        setIsSubmitting(false);
        onOpenChange(false);
        onPost();
        return 'Idea shared successfully!';
      },
      error: (err) => {
        setIsSubmitting(false);
        const permissionError = new FirestorePermissionError({ path: collectionRef.path, operation: 'create', requestResourceData: postData });
        errorEmitter.emit('permission-error', permissionError);
        return 'Failed to share idea.';
      },
    });
  };

  return (
    <Dialog open={isOpen} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-lg">
        <DialogHeader>
          <DialogTitle>Share Idea to Community</DialogTitle>
          <DialogDescription>
            Review and post this idea to the community to find collaborators.
          </DialogDescription>
        </DialogHeader>
        <Form {...form}>
          <form onSubmit={form.handleSubmit(handleSubmit)} className="space-y-4">
            <FormField
              control={form.control}
              name="title"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Title</FormLabel>
                  <FormControl>
                    <Input {...field} />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
            <FormField
              control={form.control}
              name="community"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Community</FormLabel>
                  <Select onValueChange={field.onChange} defaultValue={field.value}>
                    <FormControl>
                      <SelectTrigger>
                        <SelectValue placeholder="Select a community" />
                      </SelectTrigger>
                    </FormControl>
                    <SelectContent>
                      {communities.map(c => <SelectItem key={c} value={c}>{c}</SelectItem>)}
                    </SelectContent>
                  </Select>
                  <FormMessage />
                </FormItem>
              )}
            />
            <FormField
              control={form.control}
              name="content"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Content</FormLabel>
                  <FormControl>
                    <Textarea className="min-h-[200px] resize-y" {...field} />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
            <DialogFooter>
              <Button type="button" variant="ghost" onClick={() => onOpenChange(false)} disabled={isSubmitting}>
                Cancel
              </Button>
              <Button type="submit" disabled={isSubmitting}>
                {isSubmitting && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
                Post to Community
              </Button>
            </DialogFooter>
          </form>
        </Form>
      </DialogContent>
    </Dialog>
  );
}

export function ProjectIdeaGenerator() {
  const [ideas, setIdeas] = useState<GeneratePersonalizedProjectIdeasOutput | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [ideaToShare, setIdeaToShare] = useState<ProjectIdea | null>(null);
  const [postedIdeas, setPostedIdeas] = useState<string[]>([]);
  const [history, setHistory] = useLocalStorage<GenerationHistoryItem[]>('idea-generation-history', []);
  const [itemToDelete, setItemToDelete] = useState<string | null>(null);
  const [showClearConfirm, setShowClearConfirm] = useState(false);


  const form = useForm<z.infer<typeof formSchema>>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      skills: '',
      interests: '',
      projectPreferences: 'A web application with a social component.',
    },
  });

  const saveToHistory = useCallback((input: GeneratePersonalizedProjectIdeasInput, output: GeneratePersonalizedProjectIdeasOutput) => {
      const newHistoryItem: GenerationHistoryItem = {
          id: `gen_${Date.now()}`,
          timestamp: Date.now(),
          input,
          output,
      };
      setHistory(prev => [newHistoryItem, ...prev.slice(0, 9)]); // Keep last 10
  }, [setHistory]);

  async function onSubmit(values: z.infer<typeof formSchema>) {
    setIsLoading(true);
    setIdeas(null);
    
    const inputData = {
        skills: values.skills.split(',').map(s => s.trim()),
        interests: values.interests.split(',').map(s => s.trim()),
        projectPreferences: values.projectPreferences || 'Any type of project is fine.',
    };

    const promise = generatePersonalizedProjectIdeas(inputData);
    
    toast.promise(promise, {
        loading: 'The AI is thinking...',
        success: (result) => {
            setIdeas(result);
            setIsLoading(false);
            setPostedIdeas([]);
            saveToHistory(inputData, result);
            return 'Here are your personalized project ideas!';
        },
        error: (error) => {
            console.error('Error generating ideas:', error);
            setIsLoading(false);
            return 'There was a problem generating project ideas. Please try again.';
        }
    });
  }

  const handleShareClick = (idea: ProjectIdea) => {
    setIdeaToShare(idea);
  };

  const handlePostSuccess = () => {
    if (ideaToShare) {
      setPostedIdeas(prev => [...prev, ideaToShare.title]);
    }
  };

  const loadFromHistory = (item: GenerationHistoryItem) => {
    form.reset({
        skills: item.input.skills.join(', '),
        interests: item.input.interests.join(', '),
        projectPreferences: item.input.projectPreferences,
    });
    setIdeas(item.output);
    toast.success('Loaded previous generation from history.');
  };

  const deleteFromHistory = (id: string) => {
    setHistory(prev => prev.filter(item => item.id !== id));
    toast.success('Removed item from history.');
    setItemToDelete(null);
  };
  
  const clearHistory = () => {
    setHistory([]);
    toast.success('Cleared generation history.');
    setShowClearConfirm(false);
  }

  return (
    <>
      <AlertDialog open={!!itemToDelete} onOpenChange={(open) => !open && setItemToDelete(null)}>
        <AlertDialogContent>
            <AlertDialogHeader>
                <AlertDialogTitle>Are you sure?</AlertDialogTitle>
                <AlertDialogDescription>This will permanently delete this item from your generation history.</AlertDialogDescription>
            </AlertDialogHeader>
            <AlertDialogFooter>
                <AlertDialogCancel>Cancel</AlertDialogCancel>
                <AlertDialogAction onClick={() => itemToDelete && deleteFromHistory(itemToDelete)}>Delete</AlertDialogAction>
            </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>

       <AlertDialog open={showClearConfirm} onOpenChange={setShowClearConfirm}>
        <AlertDialogContent>
            <AlertDialogHeader>
                <AlertDialogTitle>Clear entire history?</AlertDialogTitle>
                <AlertDialogDescription>This will permanently delete all of your generated ideas history. This action cannot be undone.</AlertDialogDescription>
            </AlertDialogHeader>
            <AlertDialogFooter>
                <AlertDialogCancel>Cancel</AlertDialogCancel>
                <AlertDialogAction onClick={clearHistory}>Clear History</AlertDialogAction>
            </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>

      <ShareIdeaDialog
        idea={ideaToShare}
        isOpen={!!ideaToShare}
        onOpenChange={(isOpen) => !isOpen && setIdeaToShare(null)}
        onPost={handlePostSuccess}
      />
      <div className="space-y-8 mt-8">
        <Card>
          <CardHeader>
            <CardTitle className="font-headline flex items-center gap-2">
              <Bot className="h-6 w-6 text-primary" />
              Your Idea Co-pilot
            </CardTitle>
          </CardHeader>
          <CardContent>
            <Form {...form}>
              <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <FormField
                    control={form.control}
                    name="skills"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>Your Skills</FormLabel>
                        <FormControl>
                          <Input placeholder="e.g., React, Python, Figma" {...field} />
                        </FormControl>
                        <FormDescription>
                          List your technical skills, separated by commas.
                        </FormDescription>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                  <FormField
                    control={form.control}
                    name="interests"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>Your Interests</FormLabel>
                        <FormControl>
                          <Input placeholder="e.g., AI, Music, Gaming" {...field} />
                        </FormControl>
                        <FormDescription>
                          What topics are you passionate about?
                        </FormDescription>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                </div>
                <FormField
                  control={form.control}
                  name="projectPreferences"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Project Preferences</FormLabel>
                      <FormControl>
                        <Textarea
                          placeholder="e.g., I want to build a mobile app, or a data-heavy backend."
                          className="resize-none"
                          {...field}
                        />
                      </FormControl>
                      <FormDescription>
                        Any specific kind of project you'd like to work on?
                      </FormDescription>
                      <FormMessage />
                    </FormItem>
                  )}
                />
                <Button type="submit" disabled={isLoading}>
                  {isLoading && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
                  Generate Ideas
                </Button>
              </form>
            </Form>
          </CardContent>
        </Card>
        
        {isLoading && (
          <div className="text-center">
              <Loader2 className="mx-auto h-8 w-8 animate-spin text-primary" />
              <p className="mt-2 text-muted-foreground">The AI is thinking...</p>
          </div>
        )}

        {ideas && ideas.projectIdeas.length > 0 && (
          <div>
              <h2 className="font-headline text-3xl font-bold mb-4">Your Personalized Project Ideas</h2>
              <Accordion type="single" collapsible className="w-full">
                  {ideas.projectIdeas.map((idea, index) => {
                    const isPosted = postedIdeas.includes(idea.title);
                    return (
                      <AccordionItem value={`item-${index}`} key={index}>
                          <AccordionTrigger className='text-lg font-semibold'>{idea.title}</AccordionTrigger>
                          <AccordionContent className="space-y-4">
                              <p className="text-muted-foreground">{idea.description}</p>
                              <div>
                                  <h4 className="font-semibold flex items-center gap-2 mb-2">
                                      <BookOpen className="h-4 w-4 text-primary" />
                                      Relevant Resources
                                  </h4>
                                  <ul className="list-disc list-inside space-y-1 text-sm text-muted-foreground">
                                      {idea.relevantResources.map((resource, i) => (
                                          <li key={i}>{resource}</li>
                                      ))}
                                  </ul>
                              </div>
                              <div className="pt-2">
                                <Button
                                  size="sm"
                                  onClick={() => handleShareClick(idea)}
                                  disabled={isPosted}
                                >
                                  <Share2 className="mr-2 h-4 w-4" />
                                  {isPosted ? 'Shared!' : 'Share to Community'}
                                </Button>
                              </div>
                          </AccordionContent>
                      </AccordionItem>
                    )
                  })}
              </Accordion>
          </div>
        )}

        <div className="space-y-4">
          <div className='flex justify-between items-center'>
            <h2 className="font-headline text-3xl font-bold flex items-center gap-2">
              <History className='size-7' />
              Generation History
            </h2>
            {history.length > 0 && (
              <Button variant="destructive" size="sm" onClick={() => setShowClearConfirm(true)}>
                <Trash2 className="mr-2 h-4 w-4" /> Clear History
              </Button>
            )}
          </div>
            {history.length > 0 ? (
                <Card>
                    <CardContent className="p-4 space-y-2">
                        {history.map(item => (
                            <div key={item.id} className="group flex items-center justify-between p-3 rounded-md hover:bg-muted/50">
                                <div>
                                    <p className="font-semibold">{new Date(item.timestamp).toLocaleString()}</p>
                                    <p className="text-sm text-muted-foreground truncate">
                                        Skills: {item.input.skills.join(', ')} &middot; Interests: {item.input.interests.join(', ')}
                                    </p>
                                </div>
                                <div className="flex items-center gap-2 opacity-0 group-hover:opacity-100 transition-opacity">
                                    <Button size="sm" variant="outline" onClick={() => loadFromHistory(item)}>
                                        <Download className="mr-2 h-4 w-4" /> Load
                                    </Button>
                                    <Button size="sm" variant="destructive" onClick={() => setItemToDelete(item.id)}>
                                        <X className="h-4 w-4" />
                                    </Button>
                                </div>
                            </div>
                        ))}
                    </CardContent>
                </Card>
            ) : (
                <div className="text-center py-10 text-muted-foreground border-2 border-dashed rounded-lg">
                    <History className="mx-auto h-12 w-12" />
                    <p className="mt-4 font-semibold">No history yet.</p>
                    <p className="mt-1 text-sm">Your generated ideas will appear here.</p>
                </div>
            )}
        </div>
      </div>
    </>
  );
}
